version: "3.9"
services:
  edge-router:
    image: traefik:v1.7.34-alpine
    ports:
      - 80:80
      - 443:443
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
#    tmpfs:
#      - /var/run:rw,noexec,nosuid
    restart: always
    networks:
      - sockshop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/edge-router/traefik.toml:/etc/traefik/traefik.toml:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-08-21/dev.cams7-job.ml/fullchain4.pem:/root/dev.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-08-21/dev.cams7-job.ml/privkey4.pem:/root/dev.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/traefik.cams7-job.ml/fullchain2.pem:/root/traefik.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/traefik.cams7-job.ml/privkey2.pem:/root/traefik.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/rabbitmq.cams7-job.ml/fullchain2.pem:/root/rabbitmq.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/rabbitmq.cams7-job.ml/privkey2.pem:/root/rabbitmq.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-05/registry.cams7-job.ml/fullchain3.pem:/root/registry.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-05/registry.cams7-job.ml/privkey3.pem:/root/registry.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-07/mongo-express.cams7-job.ml/fullchain3.pem:/root/mongo-express.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-07/mongo-express.cams7-job.ml/privkey3.pem:/root/mongo-express.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/pgadmin.cams7-job.ml/fullchain3.pem:/root/pgadmin.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-09-08/pgadmin.cams7-job.ml/privkey3.pem:/root/pgadmin.cams7-job.ml.key:ro
    labels:
      - traefik.frontend.rule=Host:traefik.cams7-job.ml
      - traefik.port=8080
  mongo:
    image: mongo:5.0.9
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - sockshop
    volumes:
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/user/docker/user-db/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    labels:
      - traefik.enable=false
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=Abc@12345
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:mongo-express.cams7-job.ml
    depends_on:
      - mongo
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - CATALOGUE_DB_USER=catalogue_user
      - CATALOGUE_DB_PASS=default_password
      - CATALOGUE_DB_NAME=socksdb
    networks:
      - sockshop
    volumes:
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/catalogue/docker/catalogue-db/data/dump.sql:/tmp/dump.sql:ro
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/catalogue/docker/catalogue-db/data/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh:ro
    labels:
      - traefik.enable=false
  pgadmin4:
    image: dpage/pgadmin4:6.7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@abinbev.test
      - PGADMIN_DEFAULT_PASSWORD=Abc@12345
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:pgadmin.cams7-job.ml
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3.9.20-management
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:rabbitmq.cams7-job.ml
      - traefik.port=15672
  front-end:
    image: cams7/sockshop-front-end:1.0.1
    restart: always
#    cap_drop:
#      - all
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:dev.cams7-job.ml
  catalogue:
    image: cams7/sockshop-catalogue:1.0.3
    restart: always
    environment:
      POSTGRES_CONNECTION_STRING: "host=postgres port=5432 user=catalogue_user password=default_password dbname=socksdb sslmode=disable"
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  carts:
    image: cams7/sockshop-carts:1.0.5
    restart: always      
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - MONGODB_CONNECTION_STRING=mongodb://root:pass12345@mongo:27017/admin?tls=false
    networks:
      - sockshop
  orders:
    image: cams7/sockshop-orders:1.0.4
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - MONGODB_CONNECTION_STRING=mongodb://root:pass12345@mongo:27017/admin?tls=false
      - payment_url=http://payment
      - shipping_url=http://shipping
    networks:
      - sockshop
  shipping:
    image: cams7/sockshop-shipping:1.0.1
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
    networks:
      - sockshop
  queue-master:
    image: cams7/sockshop-queue-master:1.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
    networks:
      - sockshop
  payment:
    image: cams7/sockshop-payment:1.0.0
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  user:
    image: cams7/sockshop-user:1.0.1
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://root:pass12345@mongo:27017/admin?tls=false
    networks:
      - sockshop
#  user-sim:
#    image: weaveworksdemos/load-test:0.1.1
#    cap_drop:
#      - all
#    read_only: true
#    command: "-d 60 -r 200 -c 2 -h edge-router"
#    networks:
#      - sockshop
#    labels:
#      - traefik.enable=false
networks:
  sockshop:
    external: true
