version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.36.0
#    container_name: sockshop-monitoring-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
  nodeexporter:
    image: prom/node-exporter:v1.3.1
#    container_name: sockshop-monitoring-nodeexporter
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    ports:
      - 9100:9100
  alertmanager:
    image: prom/alertmanager:v0.24.0
#    container_name: sockshop-monitoring-alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  grafana:
    image: grafana/grafana:8.5.4
#    container_name: sockshop-monitoring-grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    links:
      - prometheus:prometheus
  importer:
    image: giantswarm/tiny-tools:3.12
#    container_name: sockshop-monitoring-grafana-importer
    depends_on:
      - grafana
    entrypoint: /bin/sh import.sh
    working_dir: /opt/grafana-import-dashboards
    volumes:
      - ./grafana:/opt/grafana-import-dashboards
    links:
      - grafana:grafana
