version: "3.9"
services:
  edge-router:
    image: traefik:v1.7.34-alpine
    ports:
      - 80:80
      - 443:443
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
#    tmpfs:
#      - /var/run:rw,noexec,nosuid
    restart: always
    networks:
      - sockshop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/edge-router/traefik.toml:/etc/traefik/traefik.toml:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-08-21/dev.cams7-job.ml/fullchain4.pem:/root/dev.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-08-21/dev.cams7-job.ml/privkey4.pem:/root/dev.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-20/traefik.cams7-job.ml/fullchain1.pem:/root/traefik.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-20/traefik.cams7-job.ml/privkey1.pem:/root/traefik.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-24/rabbitmq.cams7-job.ml/fullchain1.pem:/root/rabbitmq.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-24/rabbitmq.cams7-job.ml/privkey1.pem:/root/rabbitmq.cams7-job.ml.key:ro
    labels:
      - traefik.frontend.rule=Host:traefik.cams7-job.ml
      - traefik.port=8080
  front-end:
    image: cams7/sockshop-front-end:1.0.1
    restart: always
#    cap_drop:
#      - all
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:dev.cams7-job.ml
  catalogue:
    image: cams7/sockshop-catalogue:1.0.3
    restart: always
    environment:
      POSTGRES_CONNECTION_STRING: "host=catalogue-db port=5432 user=catalogue_user password=default_password dbname=socksdb sslmode=disable"
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  catalogue-db:
    image: cams7/sockshop-catalogue-db:1.0.0
    restart: always
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  carts:
    image: cams7/sockshop-carts:1.0.5
    restart: always      
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - MONGODB_CONNECTION_STRING=mongodb://carts-db:27017
    networks:
      - sockshop
  carts-db:
    image: mongo:5.0.9
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  orders:
    image: cams7/sockshop-orders:1.0.4
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - MONGODB_CONNECTION_STRING=mongodb://orders-db:27017
      - payment_url=http://payment
      - shipping_url=http://shipping
    networks:
      - sockshop
  orders-db:
    image: mongo:5.0.9
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  shipping:
    image: cams7/sockshop-shipping:1.0.1
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
    networks:
      - sockshop
  queue-master:
    image: cams7/sockshop-queue-master:1.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
    networks:
      - sockshop
  rabbitmq:
    image: rabbitmq:3.9.20-management
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:rabbitmq.cams7-job.ml
      - traefik.port=15672
  payment:
    image: cams7/sockshop-payment:1.0.0
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  user:
    image: cams7/sockshop-user:1.0.0
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
    networks:
      - sockshop
  user-db:
    image: cams7/sockshop-user-db:0.4.4
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
#  user-sim:
#    image: weaveworksdemos/load-test:0.1.1
#    cap_drop:
#      - all
#    read_only: true
#    command: "-d 60 -r 200 -c 2 -h edge-router"
#    networks:
#      - sockshop
#    labels:
#      - traefik.enable=false
networks:
  sockshop:
    external: true
