version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: es1
#    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - 9200:9200
  kibana:
    image: kibana:7.17.4
#    container_name: sockshop-logging-kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
  log-server:
    image: weaveworksdemos/log-server
#    container_name: sockshop-logging-log-server
    hostname: log-server
    depends_on:
      - elasticsearch
    ports:
      - '24224:24224'
  front-end:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  edge-router:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  catalogue:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  catalogue-db:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  carts:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  carts-db:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  orders:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  orders-db:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  shipping:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  queue-master:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  rabbitmq:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  payment:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  user:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  user-db:
    logging:
      driver: fluentd
    depends_on:
      - log-server
  user-sim:
    logging:
      driver: fluentd
    depends_on:
      - log-server
