version: "3.9"
services:
  edge-router:
    image: traefik:v1.7.34-alpine
    ports:
      - 80:80
      - 443:443
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
#    tmpfs:
#      - /var/run:rw,noexec,nosuid
    restart: always
    networks:
      - sockshop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/cmagalhaes/My/Desenv/DevOps/microservices-demo/edge-router/traefik.toml:/etc/traefik/traefik.toml:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-05-23/dev.cams7-job.ml/fullchain3.pem:/root/dev.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-05-23/dev.cams7-job.ml/privkey3.pem:/root/dev.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-20/traefik.cams7-job.ml/fullchain1.pem:/root/traefik.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-20/traefik.cams7-job.ml/privkey1.pem:/root/traefik.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-24/rabbitmq.cams7-job.ml/fullchain1.pem:/root/rabbitmq.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-24/rabbitmq.cams7-job.ml/privkey1.pem:/root/rabbitmq.cams7-job.ml.key:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-06/registry.cams7-job.ml/fullchain2.pem:/root/registry.cams7-job.ml.cert:ro
      - /home/cmagalhaes/My/Desenv/Certificados/22-06-06/registry.cams7-job.ml/privkey2.pem:/root/registry.cams7-job.ml.key:ro
    labels:
      - traefik.frontend.rule=Host:traefik.cams7-job.ml
      - traefik.port=8080
  registry:
    image: registry:2.8.1
    restart: always
    networks:
      - sockshop
    volumes:
      - sockshop-registry-data:/var/lib/registry
    labels:
      - traefik.frontend.rule=Host:registry.cams7-job.ml
      - traefik.port=5000
  front-end:
    image: registry.cams7-job.ml/front-end:0.3.12
    restart: always
#    cap_drop:
#      - all
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:dev.cams7-job.ml
  catalogue:
    image: registry.cams7-job.ml/catalogue:0.3.5
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  catalogue-db:
    image: registry.cams7-job.ml/catalogue-db:0.3.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  carts:
    image: registry.cams7-job.ml/carts:0.4.8
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sockshop
  carts-db:
    image: mongo:5.0.9
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  orders:
    image: registry.cams7-job.ml/orders:0.4.7
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - sockshop
  orders-db:
    image: mongo:5.0.9
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
  shipping:
    image: registry.cams7-job.ml/shipping:0.4.8
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
    networks:
      - sockshop
  queue-master:
    image: registry.cams7-job.ml/queue-master:0.3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
      - rabbitmq_host=rabbitmq
      - rabbitmq_username=guest
      - rabbitmq_password=guest
      - shipping_queue=shipping-task
      - shipping_exchange=shipping-task-exchange
      - docker_image_name=registry.cams7-job.ml/worker
      - docker_image_version=latest
      - docker_image_network=sockshop
    networks:
      - sockshop
  rabbitmq:
    image: rabbitmq:3.9.20-management
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#      - DAC_OVERRIDE
#    read_only: true
    networks:
      - sockshop
    labels:
      - traefik.frontend.rule=Host:rabbitmq.cams7-job.ml
      - traefik.port=15672
  payment:
    image: registry.cams7-job.ml/payment:0.4.3
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    networks:
      - sockshop
  user:
    image: registry.cams7-job.ml/user:0.4.4
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - NET_BIND_SERVICE
#    read_only: true
    environment:
      - MONGO_HOST=user-db:27017
    networks:
      - sockshop
  user-db:
    image: registry.cams7-job.ml/user-db:0.4.4
    restart: always
#    cap_drop:
#      - all
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    read_only: true
#    tmpfs:
#      - /tmp:rw,noexec,nosuid
    networks:
      - sockshop
    labels:
      - traefik.enable=false
#  user-sim:
#    image: weaveworksdemos/load-test:0.1.1
#    cap_drop:
#      - all
#    read_only: true
#    command: "-d 60 -r 200 -c 2 -h edge-router"
#    networks:
#      - sockshop
#    labels:
#      - traefik.enable=false
networks:
  sockshop:
    external: true

volumes:
  sockshop-registry-data:
